CREATE OR REPLACE FUNCTION CantPersonasPais
RETURN  NUMBER
IS
CANTPERSONAS NUMBER;
BEGIN
SELECT COUNT(*) into cantpersonas
FROM PERSONA P INNER JOIN
NACIONALIDADXPERSONA  NP ON P.ID=NP.IDPERSONA
INNER JOIN NACIONALIDAD N  ON NP.IDNACIONALIDAD=N.ID
INNER JOIN PAIS  PA ON N.IDPAIS=PA.ID;
END;