CREATE TABLE TODASVISITAS
(ID NUMBER,IDPERSONA NUMBER,FECHA DATE);

ALTER TABLE TODASVISITAS
    ADD CONSTRAINT pk_TodasVisitas PRIMARY KEY (id)
    USING INDEX TABLESPACE libertad_Indexes;

    
ALTER TABLE TODASVISITAS
  ADD CONSTRAINT fk_TodasVisitas_Persona FOREIGN KEY (idPersona)
    REFERENCES Persona(id);