CREATE TABLE SOLOVISITA
(ID NUMBER,IDPERSONA NUMBER,FECHA DATE);

ALTER TABLE SOLOVISITA
    ADD CONSTRAINT pk_SOLOVISITA PRIMARY KEY (id)
    USING INDEX TABLESPACE libertad_Indexes;
    
ALTER TABLE SOLOVISITA
  ADD CONSTRAINT fk_SOLOVISITA_Persona FOREIGN KEY (idPersona)
    REFERENCES Persona(id);