create or replace
PROCEDURE insert_visita_actividad(IDACTIVIDAD NUMBER,IDPERSONA NUMBER,FECHA DATE) AS
BEGIN
INSERT INTO VISITASACTIVIDAD(ID,IDACTIVIDAD,IDPERSONA,FECHAHORA)
VALUES(S_VISITAACTIVIDAD.NEXTVAL, IDACTIVIDAD,IDPERSONA,FECHA);
INSERT INTO todasvisitas(ID,idpersona, fecha)
VALUES(S_TODASVISITAS.NEXTVAL, idpersona, fecha);
COMMIT;
END;
