create or replace
PROCEDURE insert_visita_curso(IDCURSO NUMBER,IDPERSONA NUMBER,FECHA DATE) AS
BEGIN
INSERT INTO VISITACURSO(ID,IDCURSO,IDPERSONA,FECHA)
VALUES(S_VISITACURSO.NEXTVAL,IDCURSO,IDPERSONA,FECHA);

INSERT INTO todasvisitas(ID,idpersona, fecha)
VALUES(S_TODASVISITAS.NEXTVAL, idpersona, fecha);
COMMIT;
END;



