create or replace
PROCEDURE insert_visita(IDPERSONA NUMBER,FECHA DATE) AS
BEGIN
INSERT INTO SOLOVISITA(ID,IDPERSONA,FECHA)
VALUES(S_SOLOVISITA.NEXTVAL,IDPERSONA,FECHA);
INSERT INTO todasvisitas(ID,idpersona, fecha)
VALUES(S_TODASVISITAS.NEXTVAL, idpersona, fecha);
COMMIT;
END;
