DECLARE
  NOMBRE VARCHAR2(200);
  APELLIDO1 VARCHAR2(200);
  APELLIDO2 VARCHAR2(200);
  IDDISTRITO NUMBER;
  DIRECCION VARCHAR2(200);
BEGIN
  NOMBRE := 'William';
  APELLIDO1 := 'Espinoza';
  APELLIDO2 := 'Ramirez';
  IDDISTRITO := 1;
  DIRECCION := 'Rivera de Belen';

  INSERT_PERSONA(
    NOMBRE => NOMBRE,
    APELLIDO1 => APELLIDO1,
    APELLIDO2 => APELLIDO2,
    IDDISTRITO => IDDISTRITO,
    DIRECCION => DIRECCION
  );
END;
