CREATE OR REPLACE PROCEDURE insert_Nacionalidad(IDPAIS NUMBER,DESCRIPCION VARCHAR2) AS
BEGIN
INSERT INTO Nacionalidad(id, idpais, descripcion)
VALUES(s_Nacionalidad.NEXTVAL, IDPAIS,DESCRIPCION);
END;
