CREATE OR REPLACE PROCEDURE insert_EventoXPersona(IDEVENTO NUMBER,IDPERSONA NUMBER) AS
BEGIN
INSERT INTO EVENTOXPERSONA(id, idevento, idpersona)
VALUES(s_EventoXPersona.NEXTVAL, IDEVENTO,IDPERSONA);
END;
