create or replace
PROCEDURE insert_visita_evento(IDEVENTO NUMBER,IDPERSONA NUMBER,FECHA DATE) AS
BEGIN
INSERT INTO VISITASEVENTOS(ID,IDEVENTO,IDPERSONA,FECHA)
VALUES(S_VISITAEVENTO.NEXTVAL, IDEVENTO,IDPERSONA,FECHA);

INSERT INTO todasvisitas(ID,idpersona, fecha)
VALUES(S_TODASVISITAS.NEXTVAL, idpersona, fecha);
COMMIT;
END;
