--CURSO X PERIODO
CREATE TABLE CURSOXPERIODO(
  ID NUMBER(10),
  ID_CURSO NUMBER(10),
  ID_PERIODO NUMBER(20)
);
ALTER TABLE CURSOXPERIODO
  ADD CONSTRAINT pk_CURSOXPERIODO PRIMARY KEY (id)
    USING INDEX TABLESPACE libertad_Indexes;
ALTER TABLE CURSOXPERIODO
  ADD CONSTRAINT fk_CURSO_CP FOREIGN KEY (ID_CURSO)
    REFERENCES Curso(id);
ALTER TABLE CURSOXPERIODO
  ADD CONSTRAINT fk_Periodo_CP FOREIGN KEY (ID_PERIODO)
    REFERENCES Periodo(id);

--IMPARTE: CURSO X EMPLEADO
CREATE TABLE IMPARTE(
  ID NUMBER(5),
  ID_EMPLEADO NUMBER(10),
  ID_CURSOXPERIODO NUMBER(10)
);
ALTER TABLE IMPARTE
  ADD CONSTRAINT pk_IMPARTE PRIMARY KEY (id) --ID A NADA
    USING INDEX TABLESPACE libertad_Indexes; 
ALTER TABLE IMPARTE
  ADD CONSTRAINT fk_EMPLEADO_I FOREIGN KEY (ID_EMPLEADO)
    REFERENCES EMPLEADO(id);
ALTER TABLE IMPARTE
  ADD CONSTRAINT fk_CURSOXPERIODO_I FOREIGN KEY (ID_CURSOXPERIODO)
    REFERENCES CURSOXPERIODO(id);
    
--Matricula ALUMNO X CURSO
CREATE TABLE MATRICULA(
  ID NUMBER(5),
  ID_CURSOXPERIODO NUMBER(10),
  ID_ALUMNO NUMBER(10)
);
ALTER TABLE MATRICULA
  ADD CONSTRAINT pk_MATRICULA PRIMARY KEY (id) --ID A NADA
    USING INDEX TABLESPACE libertad_Indexes;
ALTER TABLE MATRICULA
  ADD CONSTRAINT fk_ALUMNO_M FOREIGN KEY (ID_ALUMNO)
    REFERENCES ALUMNO(id);
ALTER TABLE MATRICULA
  ADD CONSTRAINT fk_CURSOXPERIODO_M FOREIGN KEY (ID_CURSOXPERIODO)
    REFERENCES CURSOXPERIODO(id);

--DESERTA ALUMNO X CURSO
CREATE TABLE DESERCIONES(
  ID NUMBER(5),
  ID_CURSOXPERIODO NUMBER(5),
  ID_ALUMNO NUMBER(10),
  MOTIVO VARCHAR2(30)
);
ALTER TABLE DESERCIONES
  ADD CONSTRAINT pk_DESERTA PRIMARY KEY (id) -- ID A NADA
    USING INDEX TABLESPACE libertad_Indexes;
ALTER TABLE DESERCIONES
  ADD CONSTRAINT fk_ALUMNO_D FOREIGN KEY (ID_ALUMNO)
    REFERENCES ALUMNO(id);
ALTER TABLE DESERCIONES
  ADD CONSTRAINT fk_CURSOXPERIODO_D FOREIGN KEY (ID_CURSOXPERIODO)
    REFERENCES CURSOXPERIODO(id);
